server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-2qr6s4ri.sql.tencentcdb.com:20461/user?useSSL=false
    username: root
    password: 370105qihs0813QC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
